### ISSUE TITLE
My tasks about improving account setup in GSoC 2017

### ISSUE THREAD

**Issue by daquexian** [thunderbird/thunderbird-android#2530]
This issue is for GSoC 2017. I will work on improving account setup during this summer. The following are roughly what I will do for it.

Most of following are from [Onboarding Re-work](https://github.com/k9mail/k-9/issues/1818), any advise are welcome :D 

I'll update this issue when I make progress.

- [x] Autoconfiguration of email settings
  - [x] SRV
  - [x] Mozilla
  - [ ] Outlook (haven't been tested)
- [x] XOAuth2
  - [x] Google (issue #655)
  - [x] Hotmail
- [x] Using both client certificates and password auth (issue #793)
- [x] User friendly certificate error handling
  - [x] Expired
  - [x] Self-Signed
- [ ] Certificate viewing and pinning (issue #1798)
- [ ] User friendly TLS / SSL error handling (issue #893)
  - [ ] Only support ssl v3.0 or older
  - [ ] Only support ciphers blacklisted
- [x] Rewrite the UI

It is my honor to take part in the development of K-9 and make K-9 a better modern email client :) I will try my best in this summer.

**Comment by philipwhiuk** [comment]
I've rebased this code on my fork with the view to manually testing it this weekend and getting it ready for a 5.5xx beta release.

**Comment by kewisch** [comment]
Given 2017 has been a few years I'm going to go ahead and close this. @daquexian if you'd like to jump back into contribution please do get in touch! We may handle some of the error reporting in #8831
