### ISSUE TITLE
Disconnect's tracker protection lists in K-9 mail

### ISSUE THREAD

**Issue by chris122380** [thunderbird/thunderbird-android#6125]
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.100 - 6.602,

### Problem you are trying to solve

Trying to solve the issue of being tracked in email either from links or photos. The photo only request (Block tracking pixels #5636) has already been requested but didn't include all trackers. 

### Suggested solution

Using Disconnect's tracker protection lists to block tracking links and tracking pixels similar to how it is done by Fairemail. 

### Screenshots / Drawings / Technical details

Need to implement something like this from Fairemail FAQ - [(159) What are Disconnect's tracker protection lists?](https://github.com/M66B/FairEmail/blob/master/FAQ.md#user-content-faq159)

**Comment by chris122380** [comment]
Mozilla Thunderbird has added support for Ublock Origin allowing for this similar feature on the desktop. Would need a similar feature for mobile. Don't know if Thunderbird for mobile (K9) will support extensions or if this should be implemented like Fairemail did embedded in the email applications privacy settings.
