### ISSUE TITLE
UI/UX design work

### ISSUE THREAD

**Issue by cketti** [thunderbird/thunderbird-android#6488]
Since K-9 Mail has joined the Thunderbird project, we have access to awesome UI/UX designers/developers. This is an incomplete list of things we want to improve and that still need design work:

- [x] #6198
- [ ] Onboarding / Initial account setup – see #1818, #4721
- [ ] Restructure settings screens – Hide advanced settings by default so people new to the app won't be overwhelmed.
- [ ] Message list appearance – see #4110, #3987, #4400, #1980, #5449, 
- [ ] Show folder tree – see #630 
- [ ] Conversation view – see #6197
- [ ] Message filters – see #908
- [ ] Tags/IMAP labels – see #769
- [ ] Show remote images - see #6880

This list is mainly for us to keep track of internal design work. If you wish to contribute to a particular project, please use the corresponding issue (or create one, if there isn't one yet).

**Comment by kewisch** [comment]
There will be ongoing work to improve the UX, let's close this in favor of individual issues
