### ISSUE TITLE
[EPIC] White Label Architecture

### ISSUE THREAD

**Issue by wmontwe** [thunderbird/thunderbird-android#7807]
We will be implementing a modular white-label architecture to improve the development process for our Thunderbird for Android and K-9 Mail applications. This new structure will allow us to configure brand-specific details either during build or at runtime while maintaining a consistent core functionality. The proposed (#7805) architecture consists of application modules and a common module as follows:

**Application Modules:**

1. Thunderbird for Android: `app-thunderbird`
2. K-9 Mail: `app-k9mail`

These modules will contain app-specific implementations, configurations, resources, and startup logic. They will only depend on the `app-common` module for shared functionalities and selectively integrate other modules as needed to configure app-specific functionality.

**App Common Module:**

1. `app-common`: This module will act as the central integration point for shared code among the applications. It will contain the core functionality, shared resources, and configurations that are common to both apps.

### Tasks

- [x] Create `app-thunderbird` and `app-k9mail` modules for application-specific code and configurations and include them in the project structure
  - #7494
  - #7779
- [x] Create a `app-common` module containing shared functionality, resources, and configurations for both applications. #8000
- [x] Create an app name provider #7924
- [ ] Migrate code from the existing structure to the new modules while ensuring minimal disruption to ongoing development.
- [x] Migrate app widgets to work with both apps #7933
- [ ] Provide necessary documentation and resources for developers to help them get started with the new architecture.
- [x] Test the new architecture thoroughly to ensure it meets our performance, scalability, and security requirements.

**Comment by kewisch** [comment]
@wmontwe wondering if we can close this one, I see there are two tasks left. If they still need to be done let's maybe resolve them for after the release or decide against them? This would help with closure.
